---
title: "USGS"
author: "Christian Lutz"
date: '2022-08-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

installations
```{r installations}
install.packages("rJava")
install.packages("devtools")
devtools::install_github("ropensci/tabulizer", args="--no-multiarch")

```


Set up
```{r setup, include=FALSE}

library(tcltk)
library(rJava)
library(tabulizer)
library(tidyverse)
library(dplyr)
library(data.table)
library(plyr)
library(shiny)


getwd()
setwd("C:/Users/CLUTZ01/OneDrive - Environmental Protection Agency (EPA)/Profile/Desktop/Extraction Scripts/NY_fracking")
```




"Pesticides in Selected Water-Supply Resovoirs and Finished Drinking Water, 1999-2000: Summary of Results from a Pilot Monitoring Program
"
```{r ppmp}

##### set up ####

getwd()
setwd("C:/Users/CLUTZ01/OneDrive - Environmental Protection Agency (EPA)/Profile/Desktop/Extraction Scripts/USGS")
table <- as.data.frame(extract_tables('USGS_PPMP.pdf', pages = 29))
table_v2 <- table %>% select(X1)
names(table_v2$X1) <- "raw_chem_name"
table_v2 <- table_v2 %>% filter(X1!= "", X1!= "Compound (class)") 





#### splitting column to name and report_funcuse
table_v2 <- table_v2 %>% mutate(report_funcuse=(substring(table_v2$X1, nchar(table_v2$X1)-2)), raw_chem_name=substring(table_v2$X1, 1, nchar(table_v2$X1)-3)) 
table_v2 <- table_v2 %>% select(raw_chem_name, report_funcuse)


###create key df
report_funcuse <- as.vector(unique(table_v2$report_funcuse))
value <- c( "herbicide", "degradate", "insecticide")
funcuse_key <- data.frame(report_funcuse, value)
funcuse_key



#merge to fill out funcuse
table_v3 <-(merge(table_v2, funcuse_key, by = "report_funcuse"))

#final formatting
table_v3 <- table_v3 %>% select(raw_chem_name, value) 
colnames(table_v3)[2] <- "report_funcuse"
table_v3 <- table_v3[order(table_v3$raw_chem_name),]

###adding addtional info


ppmp_table <- table_v3 %>% mutate(data_document_id="1371480", data_document_filename="USGS_PPMP.pdf", doc_date="2001", raw_category="", cat_code="", description_cpcat="", cpcat_code="", cpcat_sourcetype="ACToR Assays and Lists
", component="", chem_detected_flag="", raw_cas="")

#re-order columns
col_order <- c("data_document_id","data_document_filename","doc_date","raw_category","raw_cas","raw_chem_name", "report_funcuse","cat_code","description_cpcat","cpcat_code","cpcat_sourcetype", "component", "chem_detected_flag")


ppmp_table
ppmp_table <- ppmp_table[,col_order]


```



"Pesticides in the Nation's Streams and Ground Water, 1992-2001"

```{r PestClass}

#set-up
getwd()
setwd("C:/Users/CLUTZ01/OneDrive - Environmental Protection Agency (EPA)/Profile/Desktop/Extraction Scripts/USGS")
pestclass_tables <- extract_tables('USGS_PestClass.pdf', pages = 163:165)
pestclass_2ndtable <- extract_tables('USGS_PestClass.pdf', pages = 164, area = list(c(183.744,42.264,739.728,547.560)))



#extract columns from tables and bind rows together
table1 <- cbind(pestclass_tables[[1]][,1],pestclass_tables[[1]][,2])
table2 <- cbind(pestclass_2ndtable[[1]][,1],pestclass_2ndtable[[1]][,3])
table3 <- cbind(pestclass_tables[[3]][,1],pestclass_tables[[3]][,2])
pestclass_table <- as.data.frame(rbind(table1,table2,table3))



#removing extraneous rows
full_pesttable_v2 <- pestclass_table %>% filter(V1 != "", V2 != "")

#separate functional use and cas number
full_pesttable_v3 <- separate(full_pesttable_v2, V2, into = c("funcuse", "cas"), sep = " (?=[^ ]*$)")


##renaming rows
names(full_pesttable_v3)[3] <- "raw_cas"
names(full_pesttable_v3)[1] <- "raw_chem_name"
names(full_pesttable_v3)[2] <- "report_funcuse"


###add additional info

pest_class <- full_pesttable_v3 %>% mutate(data_document_id="1371477", data_document_filename="USGS_PestClass.pdf", doc_date="2001", raw_category="", cat_code="", description_cpcat="", cpcat_code="", cpcat_sourcetype="ACToR Assays and Lists
", component="", chem_detected_flag="")

#re-ording columns

col_order <- c("data_document_id","data_document_filename","doc_date","raw_category","raw_cas","raw_chem_name", "report_funcuse","cat_code","description_cpcat","cpcat_code","cpcat_sourcetype", "component", "chem_detected_flag")

pest_class <- pest_class[,col_order]


```


"Distribution of Major Herbicides in Ground Water of the United States" - extracted manually



Combining tables and writing to csv for upload
```{r}
usgs_tables <- rbind(ppmp_table, pest_class)
write.csv(usgs_tables, "C:/Users/CLUTZ01/OneDrive - Environmental Protection Agency (EPA)/Profile/Desktop/Extraction Scripts/USGS\\usgs_tables.csv", row.names = FALSE)
```





















